[workspace]

members = [
    "bingushack",
    "jni_mappings",
    "mappings_macro",
    "bingus_modules",
    "module_macro_derive",
    "bingus_ui",
    "bingus_client",
    "bingus_settings",
    "setting_macro_derive",
    "macro_common",
]