[package]
name = "bingus_ui"
version = "0.1.0"
edition = "2021"

[dependencies]
eframe = { path = "../lib/egui/crates/eframe" }
bingus_module = { path = "../bingus_module" }
bingus_setting = { path = "../bingus_setting" }
