[package]
name = "jni_mappings"
version = "0.1.0"
edition = "2021"

[dependencies]
jni = { version = "0.20.0", features = ["invocation"] }
mappings_macro = { path = "../mappings_macro" }
goldberg = "0.1.0"